//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.purdue.fw.api;

import java.util.UUID;

import com.purdue.fw.model.Packet;
import com.hp.api.NotFoundException;

import com.hp.api.Id;

import java.util.Collection;

/**
 * Sample Packet service interface.
 */
public interface PacketService {

    /**
     * Get all Packet items.
     *
     * @return collection of all Packet items
     */
    public Collection<Packet> getAll();

    /** 
     * Creates a new Packet entity.
     *
     * @param id unique id to be assigned to the new Packet entity.
     * @param name Packet name
     * @return newly created Packet
     */
    public Packet create(String name);

    /**
     * Get the Packet with the specified unique id.
     *
     * @param uid unique id of the Packet entity to be retrieved
     * @return Packet with the given unique id
     * @throws NotFoundException if the requested Packet was not found
     */
    public Packet get(Id<Packet, UUID> id);

    /**
     * Delete the Packet with the specified id.
     *
     * @param uid unique id of the Packet entity to be deleted
     * @return deleted Packet
     * @throws NotFoundException if the requested Packet was not found
     */
    public void delete(Id<Packet, UUID> id);

}
