//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.purdue.fw.api;

<<<<<<< HEAD
import com.hp.of.lib.OpenflowException;


=======
>>>>>>> 21b88459bd74932e04a93ea771e39b6032304d45
public interface PacketService {

    /**
     * Get the DDoS with the specified unique id.
     *
     * @param ip_src ip_src
     * @param ip_dst ip_dst
     * @param port_src port_src
     * @param port_dst port_dst
     * @throws Exception if the requested DDoS was not found
     */
	public void createAndSendMod(String ip_src, String ip_dst, int port_src,
			int port_dst) throws Exception;

	public String stopCapture(String ip_src, String ip_dst, int src_port,
			int dst_port) throws Exception;
}
