/*
  (c) Copyright 2012 Hewlett-Packard Development Company, L.P.
  Autogenerated
 */

// JSLint directive...
/*global $: false, SKI: false */

(function (api) {
    'use strict';

    var f = api.fn,          // general functions API
        nav = api.nav;       // navigation model API

    f.trace('including fw-nav.js');

    // Add a new category and new item
    nav.insertCategoryAfter('c-tasks', 'c-fw', [
        nav.item('n-screen', 'screen'),
        nav.item('n-screen2', 'screen2')
        //nav.item('n-fw', 'fw')
    ]);

    //nav.insertCategoryAfter('c-tasks', 'c-screen', [
    //    nav.item('n-screen', 'screen', 'square')
    //]);

    // Add a new item to an existing category
    //nav.insertItemsBefore('n-exportLogs'), [
    //    nav.item('n-fw-task', 'fwTask', 'square')
    //]);

}(SKI));
