/*
   (c) Copyright 2012 Hewlett-Packard Development Company, L.P.
   Autogenerated
   */

// JSLint directive...
/*global $: false*/

(function (api) {
  'use strict';

  //framework APIs
  var fn_api = api.fn,       //general API
      def_api = api.def,     //application definition API
      view_api = api.view;   //view API

  // snap-in libs
  var tags_api = api.lib.htmlTags,
      widget_api = api.lib.widgetFactory;

  fn_api.trace('including screen.js');
  
  function create(view) {
    var div = tags_api.div({cls: 'textView'}).append(tags_api.h2('Enter Required Information')),

        IP_field1 = widget_api.textField({
          label: 'IP 1:',
          ph: 'Enter IP 1',
          //on: {
          //  keyup: function () {
          //    result.html(this.value());
          //  }
          //}
        }),

        IP_field2 = widget_api.textField({
          label: 'IP 2:',
          ph: 'Enter IP 2',
          //on: {
          //  keyup: function () {
          //    result.html(this.value());
          //  }
          //}
        }),

        port_field1 = widget_api.textField({
          label: 'Port 1:',
          ph: 'Enter Port 1',
          //on: {
          //  keyup: function () {
          //    result.html(this.value());
          //  }
          //}
        }),

        port_field2 = widget_api.textField({
          label: 'Port 2:',
          ph: 'Enter Port 2'
          //on: {
          //  keyup: function () {
          //    result.html(this.value());
          //  }
          //}
        }),

        row1 = tags_api.div({css: {margin: 45}}).append(IP_field1, IP_field2),
        row2 = tags_api.div({css: {margin: 45}}).append(port_field1, port_field2);
    
    return div.append(row1).append(row2)
  }

  function load(view) {
    var lion = view.lion;

    view_api.setToolbar(
        widget_api.button({
          icon: 'play',
          text: lion('tbStart'),
          click: function () {
            console.log(view)
            //alert('IP1: ' + IP_field1.value() + '\n' + 'IP2: ' + IP_field2.value() + '\n'
              //+ 'Port 1: ' + port_field1.value() + '\n' + 'Port 2:' + port_field2.value());
          }
        }),

        widget_api.button({
          icon: 'stop',
          text: lion('tbStop'),
          click: function () {
          }
        })
    );
  }


  def_api.addView('screen', {
    create: create,
    load: load
  });
}(SKI));
        
  //function dlg(view, titleKey, text) {
  //  var dlgDiv = tags_api.div( {
  //    attr: {
  //      id: view.mkId('dlg'),
  //      title: view.lion(titleKey)
  //    }
  //  }).append(tags_api.p(text)),
  //      $dlg = dlgDiv.domFrag(),
  //      actions = {};
  //
  //  actions[view.lion('close')] = function () {
  //    $(this).dialog("close").dialog('destory');
  //  };
  //
  //  $dlg.dialog({
  //    width: 600,
  //    buttons: actions
  //  });
  //
  //}
  //
  //// Load a view
  //function load(view) {
  //  var lion = view.lion;
  //
  //
  //  view_api.setToolbar(
  //      widget_api.button({
  //        text: lion('tbDeploy'),
  //        click: function () {
  //          dlg(view, 'deployDlg', 'This is where...');
  //        }
  //      })
  //      );
  //}
  //
  //// Add the empty view
  //def_api.addView('screen', {
  //  load: load
  //});
