//  (c) Copyright 2013 Hewlett-Packard Development Company, L.P.
//  Autogenerated
package com.purdue.fw.model;

/**
 * Packet sort attribute.
 */
public enum PacketSortAttribute {

    /** Sorts by name */
    NAME

}
